// Formato de cada pregunta: [enunciado, respuesta correcta, distractor1, distractor2, distractor3]
// El orden de las opciones se baraja al jugar.
const LEVELS = [
  {
    name: "Verb tenses",
    topic: "Tiempos verbales",
    q: [
      ["By the time we arrived, the film ____.", "had already started", "already started", "has already started", "was already starting"],
      ["I ____ in this company since 2018.", "have worked", "work", "am working", "worked"],
      ["While she ____ dinner, the phone rang.", "was cooking", "cooked", "has cooked", "had cooked"],
      ["This time next week, I ____ on a beach in Greece.", "will be lying", "will lie", "lie", "have lain"],
      ["She ____ in the village for ten years before she moved to London.", "had lived", "has lived", "lives", "was living"],
      ["I ____ in the garden all morning, so I'm exhausted.", "have been working", "work", "am working", "will have worked"],
      ["He usually walks to work, but today he ____ the bus.", "is taking", "takes", "has taken", "took"],
      ["I ____ my keys, so I can't open the door.", "have lost", "lose", "was losing", "had lost"],
      ["When I was a child, we ____ to the seaside every summer.", "used to go", "were used to go", "use to go", "have gone"],
      ["By next June, they ____ the house.", "will have built", "will build", "are building", "have built"],
      ["She ____ TV when the power went out.", "was watching", "watched", "has watched", "watches"],
      ["I ____ him since we were at school.", "have known", "know", "knew", "am knowing"],
      ["The train ____ at 6:15 tomorrow morning.", "leaves", "left", "has left", "had left"],
      ["He was exhausted because he ____ all night.", "had been driving", "has been driving", "drives", "is driving"],
      ["Look at those black clouds! It ____.", "is going to rain", "rains", "will have rained", "has rained"],
      ["How long ____ English?", "have you been learning", "do you learn", "did you learn", "are you learning"],
      ["I ____ you a postcard as soon as I arrive.", "will send", "send", "would send", "have sent"],
      ["As soon as she ____ the news, she called her mother.", "heard", "was hearing", "has heard", "hears"],
      ["The children ____ when we got home, so the house was quiet.", "had fallen asleep", "have fallen asleep", "would fall asleep", "are falling asleep"],
      ["\"Have you ever been to Japan?\" \"Yes, I ____ there in 2019.\"", "went", "have been", "was going", "have gone"]
    ]
  },
  {
    name: "Conditionals & wishes",
    topic: "Condicionales y deseos",
    q: [
      ["If I ____ you, I would apologise.", "were", "am", "will be", "had been"],
      ["If she had studied harder, she ____ the exam.", "would have passed", "would pass", "will pass", "had passed"],
      ["I wish I ____ more free time.", "had", "have", "would have", "will have"],
      ["Unless you ____ now, you'll miss the bus.", "leave", "don't leave", "will leave", "left"],
      ["If it rains tomorrow, we ____ the picnic.", "will cancel", "would cancel", "cancelled", "would have cancelled"],
      ["I wish I ____ that email yesterday.", "hadn't sent", "didn't send", "wouldn't send", "haven't sent"],
      ["If he ____ earlier, he wouldn't be so tired now.", "had gone to bed", "went to bed", "goes to bed", "would go to bed"],
      ["____ you need any help, just call me.", "Should", "Would", "Did", "Could"],
      ["If I won the lottery, I ____ my job.", "would quit", "will quit", "would have quit", "quit"],
      ["I'd rather you ____ smoke in here.", "didn't", "don't", "won't", "haven't"],
      ["It's time we ____ home.", "went", "go", "will go", "are going"],
      ["____ the traffic been better, we would have arrived on time.", "Had", "If", "Would", "Have"],
      ["If only I ____ how to swim!", "knew", "know", "will know", "would know"],
      ["As long as you ____ the rules, you can stay.", "follow", "will follow", "would follow", "have followed"],
      ["Had I known about the problem, I ____ you.", "would have told", "would tell", "will tell", "told"],
      ["If you heat ice, it ____.", "melts", "would melt", "will have melted", "melted"],
      ["If I ____ harder at school, I might have a better job now.", "had worked", "worked", "would have worked", "work"],
      ["I'll lend you the car provided that you ____ it carefully.", "drive", "will drive", "would drive", "drove"],
      ["If she hadn't missed the flight, she ____ in Rome now.", "would be", "would have been", "will be", "is"],
      ["Suppose you ____ the chance, would you live abroad?", "had", "have", "would have", "will have"]
    ]
  },
  {
    name: "Passive & causative",
    topic: "Voz pasiva y causativa",
    q: [
      ["The bridge ____ in 1932.", "was built", "built", "has built", "is building"],
      ["English ____ all over the world.", "is spoken", "speaks", "is speaking", "spoken"],
      ["I had my car ____ yesterday.", "repaired", "repair", "repairing", "to repair"],
      ["The report ____ by Friday.", "will have been finished", "will finish", "will be finishing", "has finished"],
      ["She's having her hair ____ tomorrow.", "cut", "cutting", "to cut", "cuts"],
      ["The new law ____ at the moment.", "is being discussed", "is discussing", "discusses", "has discussed"],
      ["He is said ____ a millionaire.", "to be", "be", "being", "is"],
      ["The room ____ yet.", "hasn't been cleaned", "hasn't cleaned", "isn't cleaning", "didn't clean"],
      ["We ____ the windows cleaned every month.", "have", "make", "do", "let"],
      ["The thief ____ by the police last night.", "was arrested", "arrested", "has arrested", "was arresting"],
      ["The painting is believed ____ stolen in 1990.", "to have been", "to be", "being", "to had been"],
      ["I don't like ____ what to do.", "being told", "to tell", "telling", "told"],
      ["The children ____ by their grandparents while we're away.", "will be looked after", "will look after", "have looked after", "would looked after"],
      ["He had his phone ____ on the train.", "stolen", "steal", "stealing", "to steal"],
      ["This form ____ by all applicants.", "must be completed", "must complete", "must be completing", "must have completed"],
      ["The cake ____ by my sister, not by me.", "was made", "made", "has made", "was making"],
      ["\"Where's my laptop?\" \"It ____ at the moment.\"", "is being repaired", "is repairing", "repairs", "has repaired"],
      ["They ____ the house painted last week.", "had", "made", "did", "were"],
      ["She doesn't like ____ in public.", "being photographed", "photographing", "to photograph", "photographed"],
      ["Several people ____ in the accident.", "were injured", "injured", "have injured", "were injuring"]
    ]
  },
  {
    name: "Reported speech",
    topic: "Estilo indirecto",
    q: [
      ["She told me she ____ me the next day.", "would call", "will call", "calls", "is calling"],
      ["He asked me where ____.", "I lived", "do I live", "did I live", "I do live"],
      ["\"Don't touch it!\" → She told me ____ it.", "not to touch", "don't touch", "to not touching", "not touch"],
      ["He said he ____ there the day before.", "had been", "was being", "has been", "is"],
      ["\"Have you finished?\" → She asked if I ____.", "had finished", "have finished", "would finish", "finish"],
      ["The teacher ____ us to be quiet.", "told", "said", "spoke", "talked"],
      ["She ____ me that she had never seen him before.", "told", "said", "spoke", "asked"],
      ["He accused me ____ the money.", "of stealing", "to steal", "for stealing", "stealing"],
      ["She suggested ____ to the cinema.", "going", "to go", "that we to go", "go"],
      ["He admitted ____ the window.", "breaking", "to break", "break", "that broke"],
      ["\"I'll help you,\" he said. → He ____ to help me.", "promised", "suggested", "denied", "admitted"],
      ["I asked her whether she ____ to come with us.", "wanted", "would wants", "was want", "had wanting"],
      ["He denied ____ anything about the robbery.", "knowing", "to know", "know", "that knowing"],
      ["She warned us ____ the water.", "not to drink", "don't drink", "to not drinking", "not drink"],
      ["\"Where did you put the keys?\" → He wanted to know where I ____ the keys.", "had put", "did put", "was put", "would put"],
      ["They insisted ____ paying for dinner.", "on", "to", "in", "for"],
      ["She offered ____ me home.", "to drive", "driving", "drive", "that drive"],
      ["She said that she ____ come to the party if she had time.", "would", "will", "shall", "is going"],
      ["He said, \"I was ill.\" → He said he ____ ill.", "had been", "was been", "has been", "is"],
      ["The manager congratulated her ____ the project.", "on completing", "to complete", "for complete", "in completing"]
    ]
  },
  {
    name: "Modal verbs",
    topic: "Verbos modales",
    q: [
      ["You ____ wear a seat belt. It's the law.", "must", "might", "could", "would"],
      ["Her car is outside, so she ____ be at home.", "must", "can't", "needn't", "shouldn't"],
      ["You ____ have told me earlier!", "should", "must", "can", "will"],
      ["The lights are off, so they ____ gone out.", "must have", "can have", "must", "had to"],
      ["I ____ speak French when I was five.", "could", "can", "must", "might"],
      ["You ____ come if you don't want to.", "don't have to", "mustn't", "can't", "shouldn't"],
      ["You ____ park here. It's forbidden.", "mustn't", "needn't", "don't need", "might not"],
      ["I'm not sure where Anna is. She ____ be stuck in traffic.", "might", "must", "can't", "needn't"],
      ["I ____ rather stay at home tonight.", "would", "will", "can", "must"],
      ["You ____ better see a doctor.", "had", "have", "would", "did"],
      ["____ I borrow your pen, please?", "May", "Must", "Will", "Ought"],
      ["We ____ have hurried; the train was delayed anyway.", "needn't", "mustn't", "can't", "won't"],
      ["He ____ have been over 70; he looked so young.", "can't", "mustn't", "shouldn't", "needn't"],
      ["When I lived in Paris, I ____ go to the market every Saturday.", "would", "might", "should", "ought"],
      ["____ we start the meeting?", "Shall", "Do", "Would", "Might"],
      ["You ____ to apologise to her.", "ought", "should to", "would", "might to"],
      ["I was so tired that I ____ keep my eyes open.", "couldn't", "mustn't", "shouldn't", "needn't"],
      ["She ____ be rich — she's always flying first class.", "must", "needn't", "shouldn't", "can't"],
      ["I'm sorry, I ____ have shouted at you.", "shouldn't", "mustn't", "can't", "won't"],
      ["By law, employers ____ provide a safe workplace.", "have to", "might", "would", "can't"]
    ]
  },
  {
    name: "Phrasal verbs",
    topic: "Verbos compuestos (phrasal verbs)",
    q: [
      ["The meeting was ____ until next week.", "put off", "put out", "put up", "put down"],
      ["I can't ____ with this noise any longer.", "put up", "put out", "put off", "put on"],
      ["She takes ____ her mother; they have the same smile.", "after", "over", "up", "out"],
      ["The plane ____ at 7 a.m.", "took off", "took up", "took on", "took in"],
      ["We've ____ of milk. Can you buy some?", "run out", "run off", "run away", "run over"],
      ["He ____ a great excuse to avoid the meeting.", "came up with", "came across", "came round", "came down"],
      ["Please ____ the form and return it today.", "fill in", "fill with", "fill on", "fill over"],
      ["They ____ their wedding because of the pandemic.", "called off", "called on", "called up", "called in"],
      ["I'm looking ____ to seeing you.", "forward", "after", "up", "out"],
      ["She ____ her cold quickly.", "got over", "got off", "got on", "got by"],
      ["The car ____ on the motorway.", "broke down", "broke up", "broke out", "broke in"],
      ["A fire ____ in the building last night.", "broke out", "broke off", "broke in", "broke through"],
      ["I've decided to ____ smoking.", "give up", "give in", "give out", "give away"],
      ["Can you ____ the volume? It's too loud.", "turn down", "turn out", "turn over", "turn into"],
      ["She ____ the offer because the salary was too low.", "turned down", "turned up", "turned over", "turned in"],
      ["We need to ____ this problem before it gets worse.", "deal with", "deal in", "deal out", "deal on"],
      ["I ran ____ an old friend in the supermarket.", "into", "out", "off", "away"],
      ["They tried to keep it secret, but the truth finally ____.", "came out", "came in", "came round", "came off"],
      ["Could you ____ the children while I'm out?", "look after", "look for", "look into", "look up"],
      ["The company plans to ____ 200 new staff this year.", "take on", "take off", "take over", "take up"]
    ]
  },
  {
    name: "Prepositions",
    topic: "Preposiciones",
    q: [
      ["She's very good ____ solving problems.", "at", "in", "on", "with"],
      ["I'm afraid ____ spiders.", "of", "from", "about", "at"],
      ["He apologised ____ being late.", "for", "of", "to", "about"],
      ["We depend ____ you.", "on", "of", "in", "from"],
      ["She's interested ____ photography.", "in", "on", "at", "about"],
      ["They arrived ____ the airport at noon.", "at", "in", "to", "on"],
      ["I'm responsible ____ the marketing team.", "for", "of", "about", "to"],
      ["She is married ____ a doctor.", "to", "with", "by", "for"],
      ["We're looking forward ____ the holidays.", "to", "for", "at", "on"],
      ["I'm fed up ____ waiting.", "with", "of", "about", "from"],
      ["She's allergic ____ nuts.", "to", "of", "with", "against"],
      ["He is famous ____ his paintings.", "for", "of", "by", "at"],
      ["Please send it ____ email.", "by", "with", "on", "at"],
      ["I'm not used ____ getting up early.", "to", "with", "at", "for"],
      ["She was accused ____ lying.", "of", "for", "with", "about"],
      ["The police are investigating the cause ____ the fire.", "of", "for", "to", "at"],
      ["He succeeded ____ passing the test.", "in", "at", "on", "with"],
      ["I prefer tea ____ coffee.", "to", "than", "from", "over"],
      ["He is keen ____ learning Italian.", "on", "in", "for", "at"],
      ["We congratulated him ____ his promotion.", "on", "for", "to", "with"]
    ]
  },
  {
    name: "Vocabulary & collocations",
    topic: "Vocabulario y colocaciones",
    q: [
      ["We need to ____ a decision soon.", "make", "do", "have", "get"],
      ["Can you ____ me a favour?", "do", "make", "take", "have"],
      ["She ____ a huge effort to finish on time.", "made", "did", "took", "gave"],
      ["It's a ____ of time trying to convince him.", "waste", "loss", "lack", "spend"],
      ["The government has ____ new measures to reduce pollution.", "introduced", "invented", "discovered", "developed"],
      ["Please ____ attention to what I'm saying.", "pay", "make", "do", "keep"],
      ["He ____ the world record in the 100 metres.", "broke", "cracked", "tore", "split"],
      ["We had ____ rain all night.", "heavy", "strong", "thick", "deep"],
      ["The ____ of living is very high in big cities.", "cost", "price", "value", "fee"],
      ["We must ____ the deadline, or we'll lose the contract.", "meet", "win", "catch", "do"],
      ["They had a ____ argument about money.", "heated", "boiling", "flaming", "tropical"],
      ["The film got ____ reviews from the critics.", "mixed", "blended", "joined", "shaken"],
      ["The two companies decided to join ____.", "forces", "powers", "strengths", "efforts"],
      ["I can't ____ the noise any more.", "stand", "hold", "stay", "keep"],
      ["There has been a sharp ____ in prices.", "rise", "raise", "grow", "arise"],
      ["Please ____ me know if you can come.", "let", "make", "tell", "say"],
      ["I'm ____ to hear that you passed!", "delighted", "delightful", "delight", "delighting"],
      ["She's got a great ____ of humour.", "sense", "feel", "taste", "mind"],
      ["He was ____ for breath after the run.", "gasping", "stretching", "pushing", "reaching"],
      ["The meeting has been ____ because of illness.", "postponed", "prevented", "pretended", "prolonged"]
    ]
  },
  {
    name: "Gerunds, infinitives & linkers",
    topic: "Gerundios, infinitivos y conectores",
    q: [
      ["I enjoy ____ to music.", "listening", "to listen", "listen", "to listening"],
      ["She decided ____ the job.", "to leave", "leaving", "leave", "to leaving"],
      ["He avoided ____ the question.", "answering", "to answer", "answer", "to answering"],
      ["I stopped ____ a coffee on my way to work.", "to buy", "buying", "buy", "to buying"],
      ["Remember ____ the door when you leave.", "to lock", "locking", "lock", "to locking"],
      ["The woman ____ lives next door is a doctor.", "who", "which", "whom", "whose"],
      ["This is the house ____ I grew up.", "where", "which", "who", "what"],
      ["____ it was raining, we went for a walk.", "Although", "Despite", "However", "Because"],
      ["She didn't go out ____ the bad weather.", "because of", "because", "although", "despite of"],
      ["He's the man ____ car was stolen.", "whose", "who", "which", "whom"],
      ["We'll go for a walk ____ it rains.", "unless", "although", "despite", "during"],
      ["____ being tired, she kept working.", "Despite", "Although", "However", "Even though"],
      ["I'm not used to ____ so early.", "getting up", "get up", "got up", "have got up"],
      ["It's no use ____ about it.", "worrying", "to worry", "worry", "worried"],
      ["I can't afford ____ a new car.", "to buy", "buying", "buy", "to buying"],
      ["He pretended ____ asleep.", "to be", "being", "be", "to being"],
      ["She's the girl ____ I told you about.", "whom", "which", "whose", "where"],
      ["____ he was very rich, he lived in a small flat.", "Even though", "Despite", "In spite", "However"],
      ["The film was so boring ____ I fell asleep.", "that", "as", "than", "which"],
      ["____ you work hard, you won't pass.", "Unless", "Provided", "Whereas", "Despite"]
    ]
  },
  {
    name: "Advanced mix: idioms & structures",
    topic: "Mezcla avanzada: modismos y estructuras",
    q: [
      ["That exam was a piece of ____.", "cake", "bread", "pie", "tea"],
      ["I'm feeling a bit under the ____ today.", "weather", "rain", "cloud", "sun"],
      ["It's time to ____ the bull by the horns and talk to him.", "take", "pull", "push", "turn"],
      ["She is a very ____ businesswoman.", "successful", "successive", "succeeding", "successfully"],
      ["The ____ was difficult, but we made it.", "decision", "decide", "decisive", "decided"],
      ["His ____ behaviour surprised us.", "unexpected", "unexpecting", "unexpectedly", "unexpect"],
      ["\"To break the ice\" means to ...", "start a conversation in a social situation", "end a relationship", "feel very cold", "make a mistake"],
      ["We only see each other once in a blue ____.", "moon", "sky", "sea", "day"],
      ["It's late and we're tired. Let's call it a ____.", "day", "night", "week", "stop"],
      ["She has a lot on her ____ at the moment.", "plate", "table", "dish", "tray"],
      ["Not only ____ late, but he also forgot the documents.", "did he arrive", "he arrived", "he did arrive", "arrived he"],
      ["Rarely ____ such a beautiful view.", "have I seen", "I have seen", "I saw", "did I seen"],
      ["No sooner had we left ____ it started to rain.", "than", "when", "that", "then"],
      ["Hardly had she sat down ____ the phone rang.", "when", "than", "then", "while"],
      ["It's high time you ____ looking for a job.", "started", "start", "will start", "are starting"],
      ["The decision was ____ unfair that everyone protested.", "so", "such", "too", "very"],
      ["It was ____ a good film that I watched it twice.", "such", "so", "too", "very"],
      ["____ more I think about it, the less I understand.", "The", "A", "Much", "So"],
      ["She is far ____ her sister.", "more intelligent than", "the more intelligent", "as intelligent than", "most intelligent than"],
      ["He ran as ____ as he could.", "fast", "faster", "fastest", "more fast"]
    ]
  }
];
